import { Component, Input, OnInit } from '@angular/core';
import isMobile from 'src/app/screenSize.utils';
import { UserService } from 'src/app/services/user.service';

// Generated by https://quicktype.io
export interface UserObj {
  _id: string;
  username: string;
  email: string;
  password: string;
}

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css'],
})
export class SidebarComponent implements OnInit {
  @Input('users') users: UserObj[] = [];
  mobile = false;
  constructor(private userService: UserService) {}

  ngOnInit(): void {
    // check if device is a mobile
    isMobile().subscribe((result) => (this.mobile = result));

    this.userService.allUsers().subscribe((users: any) => {
      this.users = users;
    });
  }
}
