import { Component, Input, OnInit } from '@angular/core';
import { UserService } from 'src/app/services/user.service';

// Generated by https://quicktype.io

export interface UserObj {
  _id: string;
  username: string;
  email: string;
  password: string;
}

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css'],
})
export class SidebarComponent implements OnInit {
  @Input('users') users: UserObj[] = [];
  constructor(private userService: UserService) {}

  ngOnInit(): void {
    // this.userService.allUsers().subscribe((users: any) => {
    //   this.users = users;
    // });
  }
}
